### ISSUE TITLE
没有数据库文件怎么办？

### ISSUE THREAD

**Issue by SnailMann** [SnailMann/learn-springboot-Jpa#1]
因为使用的是Spring Data Jpa，所以在配置文件里，修改`ddl-auto: update`为`ddl-auto:create`,并且新建一个名为springbootdemo的数据库即可。

修改 
```
jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
```
为
```
jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
```

经过如上配置，Jpa会在你每次运行springboot程序的时候，自动删除旧表，重新创建一个新表。旧数据清空
